# Generated by Django 4.2.5 on 2023-09-29 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantalk', '0002_moo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Moos', to=settings.AUTH_USER_MODEL),
        ),
    ]
